name: Publish Package on PyPI
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build_pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
  
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --skip-lock

      - name: Build Package
        run: |
          pipenv run python3 setup.py sdist bdist_wheel

      - name: Use Built Package
        uses: actions/cache@v3
        env:
          cache-name: cache-built-pkg
        with:
          path: dist
          key: ${{ github.ref }}

  publish_to_test_pypi:
    runs-on: ubuntu-latest
    needs: [build_pkg]
    if: contains(github.ref, 'dev')
    steps:
      - name: Use Package Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-built-pkg
        with:
          path: dist
          key: ${{ github.ref }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Add GitHub Release entry
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  publish_to_pypi:
    runs-on: ubuntu-latest
    needs: [build_pkg]
    if: "! contains(github.ref, 'dev')"
    steps:
      - name: Use Package Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-built-pkg
        with:
          path: dist
          key: ${{ github.ref }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Add GitHub Release entry
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
