name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: 
        - 3.7
        - 3.8
        - 3.9
        - 3.10
        os:
        - ubuntu
    name: test-${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
