name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        python-version: 
        - 3.7
        - 3.8
        - 3.9
        - 3.10
        os:
        - ubuntu
    name: test-${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
  
      - name: Install pipenv and dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo python -m pip install pipenv 
          pipenv install --dev --skip-lock
  
      - name: Lint and check styling
        run: |
          python -m pipenv run flake8 ./rubedo/ ./tests/ \
          --count --show-source --statistics
  
      - name: Run tests 
        run: |
          python -m pipenv run python -m pytest \
          --cov=rubedo/ \
          --cov-report xml:rubedo_coverage.xml \
          --cov-report annotate:coverage_annotations \
          --cov-report html:coverage_html \
          --junitxml=test-results-rubedo.xml \

      - uses: codecov/codecov-action@v2
        with:
          files: ./rubedo_coverage.xml
